- project:
    templates:
      - check-requirements
      - openstack-python-jobs-neutron
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-baremetal-multitenant-vlans:
            voting: false
        - networking-baremetal-multitenant-vlans-python2:
            voting: false
        - openstack-tox-lower-constraints
    gate:
      jobs:
        # - networking-baremetal-multitenant-vlans
        # - networking-baremetal-multitenant-vlans-python2
        - openstack-tox-lower-constraints
