- project:
    templates:
      - check-requirements
      - openstack-python3-jobs-neutron
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - networking-baremetal-multitenant-vlans
    gate:
      jobs:
        - networking-baremetal-multitenant-vlans
